stages:
  - test

go-vet:
  image: dbogatov/docker-sources:golang-1.13-alpine
  variables:
    CGO_ENABLED: 0
  stage: test
  script:
    - go vet ./main/
  tags:
    - docker

simple-run:
  image: dbogatov/docker-sources:golang-1.13-alpine
  stage: test
  script:
    - go run ./main/ -h
  tags:
    - docker

include:
  template: Dependency-Scanning.gitlab-ci.yml

dependency_scanning:
  variables:
    DS_DISABLE_DIND: "true"
  tags:
    - docker

gemnasium-python-dependency_scanning:
  before_script:
    - wget -O zlib.tar.gz https://www.zlib.net/zlib-1.2.11.tar.gz
    - tar xvf zlib.tar.gz
    - cd zlib-1.2.11/
    - ./configure
    - make
    - make install
    - cd ..
    - git clone https://github.com/LuaDist/libjpeg.git
    - cd libjpeg/
    - ./configure
    - make
    - make install
