stages:
  - test

go-vet:
  image: dbogatov/docker-sources:golang-1.13-alpine
  stage: test
  script:
    - go vet ./main/
  tags:
    - docker

include:
  template: Dependency-Scanning.gitlab-ci.yml

dependency_scanning:
  variables:
    DS_DISABLE_DIND: "true"
  tags:
    - docker
